version: '3.3'

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    networks:
      - traefik

  teapot:
    build: .
    container_name: "teapot"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.teapot-https.redirectscheme.scheme=https"
      - "traefik.http.routers.teapot.entrypoints=web"
      - "traefik.http.routers.teapot.rule=Host(`teapot.localhost`)"
      - "traefik.http.routers.teapot.middlewares=teapot-https@docker"
      - "traefik.http.routers.teapot-https.rule=Host(`teapot.localhost`)"
      - "traefik.http.routers.teapot-https.tls=true"
      - "traefik.http.routers.teapot-https.entrypoints=web-secure"
    volumes:
      - "./logs:/app/logs"
    networks:
      - traefik

networks:
  traefik:
#    external: true
